### ISSUE TITLE
Console Error when right clicking Sortable <li> item

### ISSUE THREAD

**Issue by jayrod718** [oribella/aurelia-sortable#37]
I get the below logged to the console when I right click inside list item using aurelia-sortable. I haven't noticed any resulting issues and the functionality is working. Any Ideas?

utils.ts:326 Uncaught TypeError: Cannot read property 'classList' of undefined
    at Sortable.stop (http://localhost:12345/scripts/vendor-bundle.js:40440:24)
    at Listener.stop (http://localhost:12345/scripts/vendor-bundle.js:39039:63)
    at Swipe.Gesture.stop (http://localhost:12345/scripts/vendor-bundle.js:39075:62)
    at Engine.endStrategy (http://localhost:12345/scripts/vendor-bundle.js:39293:31)
    at Engine.whileGestures (http://localhost:12345/scripts/vendor-bundle.js:39236:28)
    at Engine.onEnd (http://localhost:12345/scripts/vendor-bundle.js:39335:18)
    at http://localhost:12345/scripts/vendor-bundle.js:39162:59
    at http://localhost:12345/scripts/vendor-bundle.js:39500:69
    at Array.forEach (native)
    at MouseFlow.EventEmitter.emit (http://localhost:12345/scripts/vendor-bundle.js:39500:23)
    at MouseFlow.Flow.end (http://localhost:12345/scripts/vendor-bundle.js:39574:18)
    at MouseFlow.Flow.proxy (http://localhost:12345/scripts/vendor-bundle.js:39536:13)

The Sortable error seems to happen on this piece of code, I am using Aurelia CLI as well.
        Sortable.prototype.stop = function () {
            **this.target.classList.remove(this.sortingClass);**
            utils_1.utils.removeDragClone(this.dragClone);
            this.autoScroll.deactivate();
            this.childSortables.forEach(function (s) { return s.isDisabled = false; });
            this.onStop();
        };

**Comment by stoffeastrom** [comment]
Oh, that makes sense since we don't have a target in that case! We need  to ad.d a guard in the `stop` function.

**Comment by stoffeastrom** [comment]
Should be fixed in `0.12.0`
